# Generated by Django 4.2 on 2024-03-31 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_all", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "用户信息", "verbose_name_plural": "用户信息"},
        ),
    ]
