# Generated by Django 4.2 on 2024-04-08 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_all", "0002_alter_userinfo_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
